use core::char;
use serde::{Deserialize, Serialize};
use std::io;
use std::{fmt::Debug, iter::Iterator};
use super::bitvec1::{BitSliceRef};


pub struct BitIter<'a> {
    index: usize,
    slice: BitSliceRef<'a>,
}

impl<'a> BitIter<'a> {
    pub(crate) fn new(slice: BitSliceRef) -> BitIter {
        BitIter {
            index: 0,
            slice,
        }
    }
}

impl<'a> Iterator for BitIter<'a> {
    type Item = bool;

    fn next(&mut self) -> Option<Self::Item> {

        if self.slice.len() > self.index {
            let resault = self.slice.get(self.index);
            debug_assert!(resault.is_some());

            self.index += 1;

            return resault;
        }
        None
    }
}

pub struct Bits<I: Iterator<Item = io::Result<u8>>> {
    base: I,
    byte: u8,
    index: u8,
    first_take: bool
}

impl<I: Iterator<Item = io::Result<u8>>> Bits<I> {
    pub fn new(base: I) -> Self {
        let out = Bits {
            base,
            byte: 0,
            index: 0,
            first_take: true,
        };

        out
    }
}

impl<I: Iterator<Item = io::Result<u8>>> Iterator for Bits<I> {
    type Item = io::Result<bool>;

    fn next(&mut self) -> Option<io::Result<bool>> {
        if self.first_take {
            self.byte = match self.base.next() {
                Some(value) => {
                    match value {
                        Ok(value) => value,
                        Err(error) => return Some(Result::Err(error))
                    }
                },
                None => return None,
            };
            self.first_take = false;
        }

        //Check if the current byte is exhausted.
        if self.index == 8 {
            //If it is the case -> iter over the next byte.
            self.byte = match self.base.next() {
                Some(byte) => match byte {
                    Result::Ok(byte) => byte,
                    Result::Err(error) => return Some(Result::Err(error)),
                },
                None => {
                    return None;
                },
            };
            self.index = 1;
            let bit = get_bit_at(self.byte, 0);
            return Some(Result::Ok(bit));
        }

        let bit = get_bit_at(self.byte, self.index);

        self.index += 1;

        return Some(Result::Ok(bit));
    }
}

/// Set the bit at position 'n'. Bits are numbred from 0 (most significant) to 7 (least significant).
fn set_byte_at(input: &mut u8, pos: u8, value: bool) {
    assert!(pos < 8);
    *input = *input & (128 >> pos);
    if value {
        *input = *input | (128 >> pos)
    }
}

/// get the bit at position `n`. Bits are numbered from 0 (most significant) to 7 (least significant).
fn get_bit_at(input: u8, pos: u8) -> bool {
    assert!(pos < 8);
    input & (128 >> pos) != 0
}

/*
Base on the bstr crate utf-8 automaton. The copyright for the original version is reproduced below

The MIT License (MIT)

Copyright (c) 2018-2019 Andrew Gallant

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// The UTF-8 decoder provided here is based on the one presented here:
// https://bjoern.hoehrmann.de/utf-8/decoder/dfa/
//
// We *could* have done UTF-8 decoding by using a DFA generated by `\p{any}`
// using regex-automata that is roughly the same size. The real benefit of
// Hoehrmann's formulation is that the byte class mapping below is manually
// tailored such that each byte's class doubles as a shift to mask out the
// bits necessary for constructing the leading bits of each codepoint value
// from the initial byte.
//
// There are some minor differences between this implementation and Hoehrmann's
// formulation.
//
// Firstly, we make REJECT have state ID 0, since it makes the state table
// itself a little easier to read and is consistent with the notion that 0
// means "false" or "bad."
//
// Secondly, when doing bulk decoding, we add a SIMD accelerated ASCII fast
// path.
//
// Thirdly, we pre-multiply the state IDs to avoid a multiplication instruction
// in the core decoding loop. (Which is what regex-automata would do by
// default.)
//
// Fourthly, we split the byte class mapping and transition table into two
// arrays because it's clearer.
//
// It is unlikely that this is the fastest way to do UTF-8 decoding, however,
// it is fairly simple.

const ACCEPT: usize = 12;
const REJECT: usize = 0;

#[cfg_attr(rustfmt, rustfmt::skip)]
const CLASSES: [u8; 256] = [
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,  9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,
   7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,  7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
   8,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
  10,3,3,3,3,3,3,3,3,3,3,3,3,4,3,3, 11,6,6,6,5,8,8,8,8,8,8,8,8,8,8,8,
];

#[cfg_attr(rustfmt, rustfmt::skip)]
const STATES_FORWARD: &'static [u8] = &[
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  12, 0, 24, 36, 60, 96, 84, 0, 0, 0, 48, 72,
  0, 12, 0, 0, 0, 0, 0, 12, 0, 12, 0, 0,
  0, 24, 0, 0, 0, 0, 0, 24, 0, 24, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0,
  0, 24, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 36, 0, 36, 0, 0,
  0, 36, 0, 0, 0, 0, 0, 36, 0, 36, 0, 0,
  0, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

#[derive(Hash, PartialEq, Eq, Ord, PartialOrd, Clone, Debug)]
///a char or 1-3 bytes of invalid ut8.
///This is yielded by the `charsOrRaws` iterator which can be created via the ByteSlice::utf8_chunks method.
///The 'a lifetime parameter corresponds to the lifetime of the bytes that are being iterated over.
pub enum CharOrRaw {
    Char(char),
    Raw(Box<[u8]>),
}

#[derive(Clone)]
///a iterator over a char or raw invalid utf8
pub struct CharsOrRaws<I: Iterator<Item = anyhow::Result<u8>>> {
    base: I,
}

impl<I: Iterator<Item = anyhow::Result<u8>>> CharsOrRaws<I> {
    pub fn new(base: I) -> CharsOrRaws<I> {
        CharsOrRaws { base }
    }
}

impl<B: Iterator<Item = anyhow::Result<u8>>> Iterator for CharsOrRaws<B> {
    type Item = anyhow::Result<CharOrRaw>;

    #[inline]
    fn next(&mut self) -> Option<anyhow::Result<CharOrRaw>> {
        return decode_iterator(&mut self.base);
    }
}

#[inline]
pub fn decode_iterator<B>(iter: &mut B) -> Option<anyhow::Result<CharOrRaw>>
where
    B: Iterator<Item = anyhow::Result<u8>>,
{
    let mut chache: Vec<u8> = Vec::with_capacity(3);
    chache.push(match iter.next() {
        None => return None,
        Some(b) => match b {
            Result::Ok(b) if b <= 0x7F => return Some(anyhow::Result::Ok(CharOrRaw::Char(b as char))),
            Result::Ok(b) => b,
            Result::Err(err) => return Some(anyhow::Result::Err(err)),
        },
    });

    let (mut state, mut cp) = (ACCEPT, 0);
    decode_step(&mut state, &mut cp, chache[0]);
    while let Some(value) = iter.next() {
        match value {
            Result::Ok(value) => {
                chache.push(value);
                decode_step(&mut state, &mut cp, value);

                if state == ACCEPT {
                    // SAFETY: This is safe because `decode_step` guarantees that
                    // `cp` is a valid Unicode scalar value in an ACCEPT state.
                    let ch = unsafe { char::from_u32_unchecked(cp) };
                    return Some(anyhow::Result::Ok(CharOrRaw::Char(ch)));
                } else if state == REJECT {
                    // At this point, we always want to advance at least one byte.
                    return Some(anyhow::Result::Ok(CharOrRaw::Raw(chache.into_boxed_slice())));
                }
            }
            Result::Err(error) => return Some(anyhow::Result::Err(error)),
        }
    }
    None
}

#[inline]
pub fn decode_step(state: &mut usize, cp: &mut u32, b: u8) {
    let class = CLASSES[b as usize];
    if *state == ACCEPT {
        *cp = (0xFF >> class) & (b as u32);
    } else {
        *cp = (b as u32 & 0b111111) | (*cp << 6);
    }
    *state = STATES_FORWARD[*state + class as usize] as usize;
}

mod test {
    use super::BitSliceRef;
    use super::Bits;
    use super::get_bit_at;

    use std::io::{BufReader, Read, Result};

    #[test]
    fn bit_in_21() {
        let num = vec![21];
        let buf = num.as_slice();
        let boolvec: Result<Vec<bool>> = Bits::new(buf.bytes()).collect();

        assert_eq!(boolvec.unwrap(), vec![false, false, false, true, false, true, false, true]);
    }

    #[test]
    fn bit_test() {
        let num = 72;
        let mut boolvec = vec![];
        for pos in 0..8 {
            boolvec.push(get_bit_at(num, pos));
        }
        
        assert_eq!(boolvec, vec![false, true, false, false, true, false, false, false])
    }

    #[test]
    fn feature() {
        let silce = BitSliceRef::from_slice(&[255], 8);

        let iter = silce.iter();
        assert_eq!(iter.index, 0);

        let boolvec: Vec<bool> = iter.collect();

        assert_eq!(boolvec.len(), 8);
    }

    #[test]
    fn get_bit_at_127_test() {
        //127: 01111111
        let num = 127;
        let value = super::get_bit_at(num, 0);
        assert!(!value);

        for i in 1..8 {
            let value = super::get_bit_at(num, i);
            assert!(value)
        }
    }

    #[test]
    fn get_bit_at_254_test() {
        //254: 11111110
        let num = 254;
        for i in 0..7 {
            let value = super::get_bit_at(num, i);
            assert!(value)
        }
        let value = super::get_bit_at(num, 7);
        assert!(!value)
    }
}
